### ISSUE TITLE
Implement a function to configure a GPIO pin independently of other GPIO pins

### ISSUE THREAD

**Issue by skiselev** [quark-mcu/qmsi#18]
Please implement a function to configure a given GPIO pin independently of all others. 
Consider the following, common use case:
1. Device driver #1 initialized. It uses and needs to configure some GPIO pins.
2. Device driver #2 initialized. It also uses some GPIOs and needs to configure them, without disturbing the configuration from step #1.
Currently all the GPIOs need to be configured in advance using qm_gpio_set_config() before calling the initialization driver code. First of all this requires that the code that initializes GPIOs contains device-specific information (e.g. GPIO direction, interrupt polarity, etc.). This is bad for code modularity. Additionally in some cases the GPIO direction needs to be changed on the fly, and currently QMSI does not provide an easy option to do so.

**Comment by jeez** [comment]
Thanks for starting this discussion, @skiselev .

Let me give you some background. QMSI in general was designed as a true HAL, thus we wanted to have 'stateless' drivers as much as possible to keep the mandatory footprint as low as possible. This design applies very well on most of the drivers, but it does bring up some questioning for others. I agree GPIO is one of them.

The trade-off on this case got leaned towards API alignment, as we try really hard to keep consistency across the drivers.

In general, but also in your specific example, if an application needs to change one or a few GPIO pins after the first time the GPIO port is configured, it should keep its instance of qm_gpio_port_config_t alive during its entire life cycle, modifying it at will and calling qm_gpio_set_config() over and over.

If we add a new set of APIs for modifying one PIN only, and qm_gpio_set_config() is still used initially, you would get a penalty on footprint due to the new code added. The .text cost here should be similar to the approach I mentioned above, thus the only true benefit of adding these APIs would be having a more direct way of achieving that.

Now, what do you think about the approach outlined above?

Also, I'm not sure I follow your claim here: 

> First of all this requires that the code that initializes GPIOs contains device-specific information (e.g. GPIO direction, interrupt polarity, etc.). This is bad for code modularity.

Besides the driver callback, everything else on a GPIO port / pins is application specific, right?

**Comment by skiselev** [comment]
@jeez thank you for describing the QMSI design considerations.
I think I'll implement a utility function for GPIO configuration using the approach that you've described (keeping qm_gpio_port_config_t in memory).

**Comment by jeez** [comment]
great, @skiselev ! Let us know if that doesn't fit your needs, ok?
