### ISSUE TITLE
UART over DMA on C1000

### ISSUE THREAD

**Issue by jouillet** [quark-mcu/qmsi#24]
Running the UART example on C1000 causes it to reset when it reaches the DMA transfer method.

**Comment by jeez** [comment]
Thanks for the report, @jouillet !

Can you please confirm which QMSI and bootloader release versions are you using?

**Comment by jouillet** [comment]
I forgot about the bootloader. I'm currently using bootloader v1.1 with QMSI v1.4. I'll update the bootloader and report back.

**Comment by jouillet** [comment]
After flashing v1.4 bootloader the example works as expected. Out of curiosity, what changes to the bootloader caused the application code to behave differently?

**Comment by jeez** [comment]
@jouillet the v1.4 of the bootloader turns on by default several security mechanisms.
I recommend reading https://github.com/quark-mcu/qm-bootloader/blob/master/doc/secure-programmers-guide.rst entirely, but your bug is related to one of the mechanisms detailed by section 5.

Most likely, that example you had was using a variable on the stack. The x86 stack is now protected against all agents but the x86 core. If the DMA agent tried to access it, then it will reset the board because this is the policy we've configured by default.

Please let me know if our documentation clarifies it or not, ok?

**Comment by jeez** [comment]
Actually, just realized you had the contrary (and older bootloader and a newer QMSI).
On this case I believe the problem was on the linker scripts. They have changed considerably now on QMSI 1.4 and that the 1.1 bootloader is out-of-sync. Probably you got into a out-of-bounds of some sort and corrupted something.
